# This is a simple config
# More info can be found at 
# https://prometheus.io/docs/alerting/latest/configuration/

route:
  group_by: ['alertname'] # groups all alerts with same name into a single notification
  group_wait: 1m # how long to buffer collect more alerts for the same group
  group_interval: 10m # how long to wait before sending notifications for new alerts added to a group
  repeat_interval: 1h # how long to wait before re-sending a notification already sent
  receiver: slack

receivers:
- name: 'slack'
  slack_configs: # also possible to add email config
  # visit the following to learn how to set up slack api
  # https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/
  - api_url: <put your url here>
    channel: 'put your channel name here, i.e. #foo-bar'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
